version: 2

sphinx:
  configuration: docs/rtd/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_build:
      - doxygen docs/rtd/Doxyfile

python:
  install:
    - requirements: docs/rtd/requirements.txt
