version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_build:
      - doxygen docs/rtd/Doxyfile
sphinx:
  configuration: docs/rtd/conf.py
python:
  install:
    - requirements: docs/rtd/requirements.txt
